events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    proxy_cache_path /var/cache/nginx keys_zone=s3_cache:10m max_size=1g inactive=30d use_temp_path=off;

    server {
        listen 80;

        location /sensor-reports/ {
            proxy_pass http://minio-s3:9000;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;

            # кэширование
            proxy_cache s3_cache;
            proxy_cache_valid 200 30d;
            proxy_ignore_headers Set-Cookie Cache-Control Expires;

            # удаление CORS заголовков MinIO
            proxy_hide_header 'Access-Control-Allow-Origin';
            proxy_hide_header 'Access-Control-Allow-Methods';
            proxy_hide_header 'Access-Control-Allow-Headers';

            # CORS-защита
            add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
            add_header 'Access-Control-Allow-Methods' 'GET, HEAD, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,Range' always;

            add_header Vary "Origin" always;
            add_header X-Cache-Status $upstream_cache_status always;
            add_header Content-Disposition "attachment" always;

            # ответ на OPTIONS
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
                add_header 'Access-Control-Allow-Methods' 'GET, HEAD, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,Range' always;
                return 204;
            }
        }
    }
}
